### PR TITLE
Using vignette title as link text

### PR DESCRIPTION
**Pull request by rnuske**
Following your good advise to use tools::getVignetteInfo(), it was quite easy to use vignette title as link text. 

Although, I liked the regex for finding the vignettes, which i had to retire now. But is much cleaner now and the HTML looks nicer / more CRAN-like now.

### CODE REVIEW

**Comment by unDocUMeantIt** [comment]
hi, that's great news! some remarks:
- R/roxy.html.R lines 352 ff. seem to have a weird indentation (tabs?), can you use two spaces instead?
- R/roxy.package.R lines 895/896 look like a time bomb: should the output format of tools::getVignetteInfo() change, we would get broken links with strange names, but without any warning. calling the columns by numbers is not so good, you should call them by their name. i would actually first do a test after 894 whether both needed colnames are present in `vig.info` and fail with a human readable error like `stop(simpleError("doc: the output format of tools::getVignetteInfo() is not compatible with this version of roxyPackage, please consider filing a bug report with the package authors!"))` or similar.

**Comment by rnuske** [comment]
- The help page of tools::getVignetteInfo() gave me the good feeling of longevity (the last column is still named 'PDF' to remain backward compatible). That's why I just trusted the matrix layout to stay as it is for ever ;-) But you are right, it's saver to check if I got what I asked for. Done in the recent commit.
- Indention uses only spaces. But following lines started at the same column as the opening brackets, as recommended by goodpractice. Looking again at the file, I see you indent very often only two spaces and not up-to the opening bracket. Do you want me to follow that style?

**Comment by unDocUMeantIt** [comment]
your commits are most welcome!

as for the indentation: yes, please keep the coding style as it is. i know there's various opinions out there about how to indent, over time i've experimented with several proposals and this is what i am most at ease with. most importantly, it should be consistent within a project and not jump between styles.

i was always wondering whether i should write down how i like my code formatted, or whether it becomes obvious from reading what i've released ;-) e.g., you might have noticed i always add an empty " else {}" to "if" clauses when there is no "else", because it leaves no doubt that there really _is_ none, and that it's _intentional_. i know people who find this rather confusing. there probably is no single right way for many decisions, so i chose the one i like best for my projects. hope that's ok with you!

**Comment by rnuske** [comment]
Your project, your rules. I will try to follow them. 
I might struggle a little since my code usually looks slightly different. Please remind me if I divert too far, will fix my commits.

**Pull request merged**
